// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeiroInfluencer.Data;

#nullable disable

namespace PrimeiroInfluencer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230804162022_InicialMigrationWithAddresAndProd")]
    partial class InicialMigrationWithAddresAndProd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PrimeiroInfluencer.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("NumberHouse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PublicPlace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AddressDb");
                });

            modelBuilder.Entity("PrimeiroInfluencer.Model.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("gender_prod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name_prod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("price_prod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("ProductDb");
                });
#pragma warning restore 612, 618
        }
    }
}
