// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimeiroInfluencer.Data;

#nullable disable

namespace PrimeiroInfluencer.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230801014907_CreateTableProd")]
    partial class CreateTableProd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PrimeiroInfluencer.Model.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("gender_prod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name_prod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("price_prod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("qtd_prod")
                        .HasColumnType("int");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("ProductDb");
                });
#pragma warning restore 612, 618
        }
    }
}
